version: "3"

services:
  client:
    build: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - API_URL=http://server:4000

  server:
    build: server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://localhost/todoapp

  db:
    image: mongo:3.4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
